In [2]:
import json
import pandas as pd
import glob
import re
import random
import glob
import datetime
import joblib
import numpy as np


from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn import tree
from sklearn import metrics

In [ ]:
# ANCOR_dataframe=pd.read_excel("./All-Chains-Balanced-Links/corpus_ALL.xlsx",index_col=0).iloc[:,7:]

# df=ANCOR_dataframe.copy()

# list_of_non_categorial_values={
#  'COM_RATE',
#  'DISTANCE_CHAR',
#  'DISTANCE_MENTION',
#  'DISTANCE_WORD',
#  'INCL_RATE',
#  'IS_CO_REF'}

# list_of_categorial_values= set(df.columns)-list_of_non_categorial_values

# df.fillna("VOID",inplace=True)

# list_of_lists_values=[list(df[col_name].unique()) for col_name in list_of_categorial_values]
# list_values=[str(z) for y in list_of_lists_values for z in y]
# list_values_sorted=list(np.sort(list(set(list_values))))
# list_values_sorted

In [59]:
x=ANCOR_dataframe=pd.read_excel(train[0],index_col=0)
y=ANCOR_dataframe=pd.read_excel(train[2],index_col=0)

train_mixed=pd.concat([x,y],ignore_index=True)

train=["./corpus_OTG_from_left_with_window_size_20_Train.xlsx",
"./corpus_OTG_normal_Neg_50_Train.xlsx",
"./corpus_OTG_normal_Neg_90_Train.xlsx"]


test=["./corpus_OTG_from_left_with_window_size_20_Test.xlsx"]

In [60]:
count=-1
list_output=["corpus_OTG_from_left_with_window_size_20_Test_Trained_window_size_20.xlsx",
      "corpus_OTG_from_left_with_window_size_20_Test_Trained_Neg_50.xlsx",
      "corpus_OTG_from_left_with_window_size_20_Test_Trained_Neg_90.xlsx"]
for xx in train:
    count+=1
    for yy in test:

        list_to_convert=[
                         'AMOUNT','DEF_DEM','DEF_SPLE','EVENT',
                         'EXPL','F','FONC','INDEF','LOC','M','N',
                         'NO','ORG','PERS','PL','PR','PROD','SG',
                         'TIME','UNK','VOID','YES']


        ANCOR_dataframe=pd.read_excel(xx,index_col=0).iloc[:,7:]
        ANCOR_dataframe.fillna("VOID", inplace=True)
        ANCOR_dataframe=ANCOR_dataframe.replace(list_to_convert, range(1,23)) 
        ANCOR_dataframe.drop(['m1_DEF','m2_DEF','ID_DEF'], axis=1, inplace=True)


        list_to_convert=[
                         'AMOUNT','DEF_DEM','DEF_SPLE','EVENT',
                         'EXPL','F','FONC','INDEF','LOC','M','N',
                         'NO','ORG','PERS','PL','PR','PROD','SG',
                         'TIME','UNK','VOID','YES']


        ANCOR_dataframe_t=pd.read_excel(yy,index_col=0).iloc[:,7:]
        ANCOR_dataframe_t.fillna("VOID", inplace=True)
        ANCOR_dataframe_t=ANCOR_dataframe_t.replace(list_to_convert, range(1,23)) 
        ANCOR_dataframe_t.drop(['m1_DEF','m2_DEF','ID_DEF'], axis=1, inplace=True)



        print(datetime.datetime.now().strftime("%a, %d %B %Y %H:%M:%S"))
        print(xx)
        print(yy)
        #Create a random forest Classifier
        clf = RandomForestRegressor(max_depth=10, random_state=0,n_estimators=250)

        #Train the model using the training sets
        # clf.fit(X_train, y_train)
        clf.fit(ANCOR_dataframe.iloc[:,0:-1], ANCOR_dataframe.iloc[:,-1])


        #Predict the response for test dataset
        # y_pred = clf.predict(X_test)
        y_pred = clf.predict(ANCOR_dataframe_t.iloc[:,0:-1])


        binary_y_pred=[]


        for x in y_pred:
            if x>=0.5:
                binary_y_pred.append(1)
            else:
                binary_y_pred.append(0)

        # binary_y_pred = np.array(binary_y_pred)


        ANCOR_dataframe_test_out=pd.read_excel(yy,index_col=0)
        ANCOR_dataframe_test_out["Prediction"]=y_pred
        ANCOR_dataframe_test_out.to_excel(list_output[count])
        
        from sklearn import metrics

        print("Random Forest Regression")
        print("")
        print("Precision-Pos:",metrics.precision_score(ANCOR_dataframe_t.iloc[:,-1], binary_y_pred))
        print("Recall-Pos:",metrics.recall_score(ANCOR_dataframe_t.iloc[:,-1], binary_y_pred))
        print("F1-Pos:",metrics.f1_score(ANCOR_dataframe_t.iloc[:,-1], binary_y_pred))

        print("")

        print("Precision-Neg:",metrics.precision_score(ANCOR_dataframe_t.iloc[:,-1], binary_y_pred,pos_label=False))
        print("Recall-Neg:",metrics.recall_score(ANCOR_dataframe_t.iloc[:,-1], binary_y_pred,pos_label=False))
        print("F1-Neg:",metrics.f1_score(ANCOR_dataframe_t.iloc[:,-1], binary_y_pred,pos_label=False))

        print("")
        print(datetime.datetime.now().strftime("%a, %d %B %Y %H:%M:%S"))

Wed, 18 March 2020 20:05:26
./corpus_OTG_from_left_with_window_size_20_Train.xlsx
./corpus_OTG_from_left_with_window_size_20_Test.xlsx
Random Forest Regression

Precision-Pos: 0.6997742663656885
Recall-Pos: 0.541958041958042
F1-Pos: 0.6108374384236454

Precision-Neg: 0.9829980532121999
Recall-Neg: 0.9912963811268896
F1-Neg: 0.98712977745919

Wed, 18 March 2020 20:06:22
Wed, 18 March 2020 20:06:30
./corpus_OTG_normal_Neg_50_Train.xlsx
./corpus_OTG_from_left_with_window_size_20_Test.xlsx
Random Forest Regression

Precision-Pos: 0.2925207756232687
Recall-Pos: 0.9230769230769231
F1-Pos: 0.44425746739587724

Precision-Neg: 0.996867881548975
Recall-Neg: 0.9164321706694588
F1-Neg: 0.9549592553445395

Wed, 18 March 2020 20:06:48
Wed, 18 March 2020 20:07:01
./corpus_OTG_normal_Neg_90_Train.xlsx
./corpus_OTG_from_left_with_window_size_20_Test.xlsx
Random Forest Regression

Precision-Pos: 0.6440071556350626
Recall-Pos: 0.6293706293706294
F1-Pos: 0.636604774535809

Precision-Neg: 0.9861383549104223
Recall-Neg: 0.9869772920620378
F1-Neg: 0.9865576451349142

Wed, 18 March 2020 20:07:24

In [47]:
ANCOR_dataframe_test_out

,Left_ID,Right_ID,Sub_Corpus,File_Name,chain_id,m1,m2,m1_TYPE,m2_TYPE,m1_DEF,...,ID_GENDER,ID_NUMBER,DISTANCE_MENTION,DISTANCE_WORD,DISTANCE_CHAR,EMBEDDED,ID_PREVIOUS,ID_NEXT,IS_CO_REF,Prediction
1030,adrouin_1330183875369,adrouin_1330183819833,corpus_OTG,2AP0092,-1,madame,je,N,PR,DEF_SPLE,...,YES,YES,0,0,0,NO,NaN,NO,0,0.051386
1031,adrouin_1330700250623,adrouin_1330183875369,corpus_OTG,2AP0092,-1,je,la part de mon père,PR,N,DEF_SPLE,...,YES,YES,0,2,9,NO,NaN,NO,0,0.000206
1032,adrouin_1330700250623,adrouin_1330183819833,corpus_OTG,2AP0092,-1,madame,la part de mon père,N,N,DEF_SPLE,...,YES,YES,1,3,12,NO,NO,NO,0,0.000238
1033,adrouin_1330701024749,adrouin_1330700250623,corpus_OTG,2AP0092,-1,la part de mon père,mon père,N,N,DEF_SPLE,...,NO,YES,0,0,0,YES,YES,YES,0,0.005355
1034,adrouin_1330701024749,adrouin_1330183875369,corpus_OTG,2AP0092,-1,je,mon père,PR,N,DEF_SPLE,...,NO,YES,1,5,20,NO,NaN,NO,0,0.000217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94598,mgodefroy_1331834787165,mgodefroy_1331834518958,corpus_OTG,1SB0300,0,enfant de quatre ans,le public enfant,N,N,INDEF,...,YES,YES,5,18,90,NO,NO,NO,1,0.050115
94599,mgodefroy_1331834787165,mgodefroy_1331834443350,corpus_OTG,1SB0300,0,les,le public enfant,PR,N,DEF_SPLE,...,YES,NO,9,43,226,NO,NO,NO,1,0.009067
94600,mgodefroy_1331834537248,mgodefroy_1331833990053,corpus_OTG,1SB0300,1,quatre ans,quatre ans,N,N,DEF_SPLE,...,YES,YES,19,82,454,YES,YES,NO,1,0.772126
94601,jmuzerelle_1370352000040,mgodefroy_1331833835787,corpus_OTG,1SB0300,2,divertissements,qu',N,N,INDEF,...,YES,YES,0,0,0,NO,NO,NO,1,0.092504
94602,mgodefroy_1331834738118,mgodefroy_1331834589957,corpus_OTG,1SB0300,2,les loisirs enfants,les,N,PR,DEF_SPLE,...,YES,YES,1,1,5,YES,NO,NO,1,0.457299

In [23]:
list_to_convert=[
                 'AMOUNT','DEF_DEM','DEF_SPLE','EVENT',
                 'EXPL','F','FONC','INDEF','LOC','M','N',
                 'NO','ORG','PERS','PL','PR','PROD','SG',
                 'TIME','UNK','VOID','YES']


ANCOR_dataframe=train_mixed.copy().iloc[:,7:]
ANCOR_dataframe.drop(['m1_DEF','m2_DEF','ID_DEF'], axis=1, inplace=True)
ANCOR_dataframe.fillna("VOID", inplace=True)
ANCOR_dataframe=ANCOR_dataframe.replace(list_to_convert, range(1,23)) 
ANCOR_dataframe

,m1_TYPE,m2_TYPE,m1_GP,m2_GP,m1_GENDER,m2_GENDER,m1_NUMBER,m2_NUMBER,m1_EN,m2_EN,...,ID_EN,ID_GENDER,ID_NUMBER,DISTANCE_MENTION,DISTANCE_WORD,DISTANCE_CHAR,EMBEDDED,ID_PREVIOUS,ID_NEXT,IS_CO_REF
0,16,16,12,12,6,6,18,18,14,14,...,22,22,22,0,3,19,12,12,12,0
1,16,11,12,12,6,10,18,15,14,12,...,21,12,12,0,1,7,12,12,12,0
2,16,11,12,12,6,10,18,15,14,12,...,21,12,12,1,5,31,12,12,12,0
3,11,11,12,22,10,10,15,15,12,12,...,21,22,22,0,1,4,12,12,12,0
4,16,11,12,22,6,10,18,15,14,12,...,21,12,12,1,4,25,12,12,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95182,16,11,22,22,10,10,15,18,12,12,...,21,22,12,3,21,115,12,12,12,1
95183,11,11,22,22,10,10,15,15,1,1,...,22,22,22,19,82,454,22,22,12,1
95184,11,11,12,12,10,10,15,15,12,12,...,21,22,22,26,108,575,12,12,12,1
95185,11,16,12,12,10,10,15,15,12,12,...,21,22,22,28,112,600,12,12,12,1
95186,11,16,12,12,10,10,15,15,12,12,...,21,22,22,27,112,598,12,12,12,1

In [24]:
list_to_convert=[
                 'AMOUNT','DEF_DEM','DEF_SPLE','EVENT',
                 'EXPL','F','FONC','INDEF','LOC','M','N',
                 'NO','ORG','PERS','PL','PR','PROD','SG',
                 'TIME','UNK','VOID','YES']


ANCOR_dataframe_t=pd.read_excel("./corpus_OTG_from_left_with_window_size_20_Test.xlsx",index_col=0).iloc[:,7:]
ANCOR_dataframe_t.drop(['m1_DEF','m2_DEF','ID_DEF'], axis=1, inplace=True)
ANCOR_dataframe_t.fillna("VOID", inplace=True)
ANCOR_dataframe_t=ANCOR_dataframe_t.replace(list_to_convert, range(1,23)) 
ANCOR_dataframe_t

,m1_TYPE,m2_TYPE,m1_GP,m2_GP,m1_GENDER,m2_GENDER,m1_NUMBER,m2_NUMBER,m1_EN,m2_EN,...,ID_EN,ID_GENDER,ID_NUMBER,DISTANCE_MENTION,DISTANCE_WORD,DISTANCE_CHAR,EMBEDDED,ID_PREVIOUS,ID_NEXT,IS_CO_REF
1030,11,16,12,12,6,6,18,18,14,14,...,22,22,22,0,0,0,12,21,12,0
1031,16,11,12,22,6,6,18,18,14,12,...,21,22,22,0,2,9,12,21,12,0
1032,11,11,12,22,6,6,18,18,14,12,...,21,22,22,1,3,12,12,12,12,0
1033,11,11,22,22,6,10,18,18,12,12,...,21,12,22,0,0,0,22,22,22,0
1034,16,11,12,22,6,10,18,18,14,12,...,21,12,22,1,5,20,12,21,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94598,11,11,22,12,10,10,18,18,12,12,...,21,22,22,5,18,90,12,12,12,1
94599,16,11,22,12,10,10,15,18,12,12,...,21,22,12,9,43,226,12,12,12,1
94600,11,11,22,22,10,10,15,15,1,1,...,22,22,22,19,82,454,22,22,12,1
94601,11,11,12,12,10,10,15,15,12,12,...,21,22,22,0,0,0,12,12,12,1
94602,11,16,12,12,10,10,15,15,12,12,...,21,22,22,1,1,5,22,12,12,1

In [25]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(ANCOR_dataframe.iloc[:,0:-1], ANCOR_dataframe.iloc[:,-1], test_size=0.2)

In [37]:
print(datetime.datetime.now().strftime("%a, %d %B %Y %H:%M:%S"))
print("")
#Create a random forest Classifier
clf = RandomForestRegressor(max_depth=10, random_state=0,n_estimators=250)

#Train the model using the training sets
# clf.fit(X_train, y_train)
clf.fit(ANCOR_dataframe.iloc[:,0:-1], ANCOR_dataframe.iloc[:,-1])


#Predict the response for test dataset
# y_pred = clf.predict(X_test)
y_pred = clf.predict(ANCOR_dataframe_t.iloc[:,0:-1])


binary_y_pred=[]


for x in y_pred:
    if x>=0.5:
        binary_y_pred.append(1)
    else:
        binary_y_pred.append(0)

# binary_y_pred = np.array(binary_y_pred)


from sklearn import metrics

print("Random Forest Regression")
print("")
print("Precision-Pos:",metrics.precision_score(ANCOR_dataframe_t.iloc[:,-1], binary_y_pred))
print("Recall-Pos:",metrics.recall_score(ANCOR_dataframe_t.iloc[:,-1], binary_y_pred))
print("F1-Pos:",metrics.f1_score(ANCOR_dataframe_t.iloc[:,-1], binary_y_pred))

print("")

print("Precision-Neg:",metrics.precision_score(ANCOR_dataframe_t.iloc[:,-1], binary_y_pred,pos_label=False))
print("Recall-Neg:",metrics.recall_score(ANCOR_dataframe_t.iloc[:,-1], binary_y_pred,pos_label=False))
print("F1-Neg:",metrics.f1_score(ANCOR_dataframe_t.iloc[:,-1], binary_y_pred,pos_label=False))

print("")
print(datetime.datetime.now().strftime("%a, %d %B %Y %H:%M:%S"))

joblib.dump(clf, "ANCOR_50_50_RandomForest.model")
# model=joblib.load("ANCOR_10_90_RandomForest.model")

Wed, 18 March 2020 00:58:34

Random Forest Regression

Precision-Pos: 0.7030927835051546
Recall-Pos: 0.5961538461538461
F1-Pos: 0.6452223273415326

Precision-Neg: 0.984968766267569
Recall-Neg: 0.9905765329494143
F1-Neg: 0.9877646905282391

Wed, 18 March 2020 00:59:54

['ANCOR_50_50_RandomForest.model']

In [ ]:
from sklearn.model_selection import cross_val_score
clf = RandomForestClassifier(max_depth=10, random_state=0,n_estimators=250)

scores = cross_val_score(clf, X_train, y_train, cv=10, scoring='precision')
print("Precision:"+str(scores.mean()))
scores = cross_val_score(clf, X_train, y_train, cv=10, scoring='recall')
print("Recall:"+str(scores.mean()))
scores = cross_val_score(clf, X_train, y_train, cv=10, scoring='f1')
print("F1:"+str(scores.mean()))

In [ ]:
X_train.columns[]

In [ ]:
print(datetime.datetime.now().strftime("%a, %d %B %Y %H:%M:%S"))

#Create a random forest Classifier
clf = GaussianNB()

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

from sklearn import metrics

print("Naive Bayes")
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))
print("F1:",metrics.f1_score(y_test, y_pred))

print(datetime.datetime.now().strftime("%a, %d %B %Y %H:%M:%S"))

In [ ]:
print(datetime.datetime.now().strftime("%a, %d %B %Y %H:%M:%S"))

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

from sklearn import metrics

print("Support Vector Machine")
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))
print("F1:",metrics.f1_score(y_test, y_pred))

print(datetime.datetime.now().strftime("%a, %d %B %Y %H:%M:%S"))

In [ ]:
ANCOR_dataframe_test=pd.read_excel("./All-Chains-Balanced-Links/corpus_ALL_test.xlsx",index_col=0).iloc[:,7:]
ANCOR_dataframe_test.fillna("VOID", inplace=True)
ANCOR_dataframe_test=ANCOR_dataframe_test.replace(list_to_convert, range(1,23))
model=joblib.load("ANCOR_50_50_RandomForest.model")
y_pred=model.predict(ANCOR_dataframe_test.iloc[:,0:-1])

# binary_y_pred=[]

# for x in y_pred:
#     if x>=0.6:
#         binary_y_pred.append(1)
#     else:
#         binary_y_pred.append(0)
        
        
ANCOR_dataframe_test=pd.read_excel("./All-Chains-Balanced-Links/corpus_ALL_test.xlsx",index_col=0)
ANCOR_dataframe_test["Prediction"]=y_pred
ANCOR_dataframe_test.to_excel("./All-Chains-Balanced-Links/corpus_ALL_test_with_Prediction.xlsx")


# print("Precision:",metrics.precision_score(ANCOR_dataframe_test["IS_CO_REF"], binary_y_pred))
# print("Recall:",metrics.recall_score(ANCOR_dataframe_test["IS_CO_REF"], binary_y_pred))
# print("F1:",metrics.f1_score(ANCOR_dataframe_test["IS_CO_REF"], binary_y_pred))

In [35]:
np.mean(ANCOR_dataframe_t.iloc[:,-1])

0.03608149876994891

In [56]:
df=pd.read_excel("corpus_OTG_normal_Neg_90.xlsx",index_col=0)
df[df["IS_CO_REF"]==1].shape

(1969, 36)

In [57]:
df.shape

(19883, 36)

In [58]:
1969/19883

0.09902932153095609

In [107]:
ANCOR_dataframe=pd.read_excel("./corpus_ALL.xlsx",index_col=0).iloc[:,7:]

In [108]:
xx=list(ANCOR_dataframe.columns)

In [117]:
list_a=[]
yy=[ANCOR_dataframe[x].unique().tolist() for x in xx]
zz=list(set([x for y in yy for x in y]))
zz=zz[1:]
zz.sort()
zz

['AMOUNT',
 'DEF_DEM',
 'DEF_SPLE',
 'EVENT',
 'EXPL',
 'F',
 'FONC',
 'INDEF',
 'LOC',
 'M',
 'N',
 'NO',
 'ORG',
 'PERS',
 'PL',
 'PR',
 'PROD',
 'SG',
 'TIME',
 'UNK',
 'YES']

In [72]:
ANCOR_dataframe.columns

Index(['m1_TYPE', 'm2_TYPE', 'm1_DEF', 'm2_DEF', 'm1_GP', 'm2_GP', 'm1_GENDER',
       'm2_GENDER', 'm1_NUMBER', 'm2_NUMBER', 'm1_EN', 'm2_EN', 'ID_FORM',
       'ID_SUBFORM', 'INCL_RATE', 'COM_RATE', 'ID_DEF', 'ID_GP', 'ID_TYPE',
       'ID_EN', 'ID_GENDER', 'ID_NUMBER', 'DISTANCE_MENTION', 'DISTANCE_WORD',
       'DISTANCE_CHAR', 'EMBEDDED', 'ID_PREVIOUS', 'ID_NEXT', 'IS_CO_REF'],
      dtype='object')

In [114]:
xx=['m1_TYPE', 'm2_TYPE', 'm1_DEF', 'm2_DEF', 'm1_GENDER',
       'm2_GENDER', 'm1_NUMBER', 'm2_NUMBER', 'm1_EN', 'm2_EN', 'ID_FORM',
       'ID_SUBFORM', 'ID_DEF', 'ID_TYPE',
       'ID_EN', 'ID_GENDER', 'ID_NUMBER', 'EMBEDDED', 'ID_PREVIOUS', 'ID_NEXT']

In [111]:
xx

['m1_TYPE',
 'm2_TYPE',
 'm1_DEF',
 'm2_DEF',
 'm1_GENDER',
 'm2_GENDER',
 'm1_NUMBER',
 'm2_NUMBER',
 'm1_EN',
 'm2_EN',
 'ID_FORM',
 'ID_SUBFORM',
 'INCL_RATE',
 'COM_RATE',
 'ID_DEF',
 'ID_TYPE',
 'ID_EN',
 'ID_GENDER',
 'ID_NUMBER',
 'DISTANCE_MENTION',
 'DISTANCE_WORD',
 'DISTANCE_CHAR',
 'EMBEDDED',
 'ID_PREVIOUS',
 'ID_NEXT',
 'IS_CO_REF']