In [2]:
import json
import pandas as pd
import glob
import re
import random
import glob
import random

In [3]:
ANCOR_dataframe=pd.read_excel("./corpus_OTG_normal_Neg_50.xlsx",index_col=0)
ANCOR_dataframe

,Left_ID,Right_ID,Sub_Corpus,File_Name,chain_id,m1,m2,m1_TYPE,m2_TYPE,m1_DEF,...,ID_EN,ID_GENDER,ID_NUMBER,DISTANCE_MENTION,DISTANCE_WORD,DISTANCE_CHAR,EMBEDDED,ID_PREVIOUS,ID_NEXT,IS_CO_REF
0,sduchon_1343592771994,sduchon_1343592235138,corpus_OTG,2AG0578,-1,la région,une carte de la région,N,N,DEF_SPLE,...,NaN,YES,YES,1,4,19,YES,NO,NO,0
1,sduchon_1343587992819,sduchon_1343587897938,corpus_OTG,2AG0578,-1,je,vous,PR,PR,DEF_SPLE,...,YES,YES,YES,14,57,310,NO,NO,NO,0
2,sduchon_1343588066343,sduchon_1343593398550,corpus_OTG,2AG0578,-1,des documents,Grenoble,N,N,INDEF,...,NaN,NaN,NaN,16,76,389,NO,NO,NO,0
3,sduchon_1343592197547,sduchon_1343588006411,corpus_OTG,2AG0578,-1,les lieux touristiques,je,N,PR,DEF_SPLE,...,NaN,NO,NO,7,40,193,NO,NO,NO,0
4,sduchon_1343587897938,sduchon_1343587982444,corpus_OTG,2AG0578,-1,je,je,PR,PR,DEF_SPLE,...,YES,YES,YES,8,35,190,YES,NO,YES,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4419,mgodefroy_1331834443350,mgodefroy_1331834518958,corpus_OTG,1SB0300,0,les,enfant de quatre ans,PR,N,DEF_SPLE,...,NaN,YES,NO,3,21,115,NO,NO,NO,1
4420,mgodefroy_1331834537248,mgodefroy_1331833990053,corpus_OTG,1SB0300,1,quatre ans,quatre ans,N,N,DEF_SPLE,...,YES,YES,YES,19,82,454,YES,YES,NO,1
4421,mgodefroy_1331834589957,mgodefroy_1331833835787,corpus_OTG,1SB0300,2,divertissements,les loisirs enfants,N,N,INDEF,...,NaN,YES,YES,26,108,575,NO,NO,NO,1
4422,mgodefroy_1331833835787,mgodefroy_1331834738118,corpus_OTG,1SB0300,2,divertissements,les,N,PR,INDEF,...,NaN,YES,YES,28,112,600,NO,NO,NO,1
4423,mgodefroy_1331834738118,jmuzerelle_1370352000040,corpus_OTG,1SB0300,2,qu',les,N,PR,INDEF,...,NaN,YES,YES,27,112,598,NO,NO,NO,1

In [7]:
sub_corpus_num=0
rate=0

while (sub_corpus_num!=2 or not(rate>=.2000 and rate<.22) ):
    sub_corpus_files=ANCOR_dataframe["File_Name"].unique().tolist()
    sub_corpus_files_test=random.sample(sub_corpus_files, 45)
    sub_corpus_files_train=[file for file in sub_corpus_files if file not in sub_corpus_files_test]


    ANCOR_dataframe_train=ANCOR_dataframe[ANCOR_dataframe["File_Name"].isin(sub_corpus_files_train)]
    ANCOR_dataframe_test=ANCOR_dataframe[ANCOR_dataframe["File_Name"].isin(sub_corpus_files_test)]

    rate=ANCOR_dataframe_test.shape[0]/ANCOR_dataframe_train.shape[0]
    sub_corpus_num=(ANCOR_dataframe_train["Sub_Corpus"].unique().shape[0]+
                    ANCOR_dataframe_test["Sub_Corpus"].unique().shape[0])
    
print(len(sub_corpus_files_test))
print(len(sub_corpus_files_train))
print(rate)
print(sub_corpus_num)

45
210
0.21806167400881057
2

In [ ]:
ANCOR_dataframe_train.to_excel("./All-Chains-Balanced-Links/corpus_ALL_train.xlsx")
ANCOR_dataframe_test.to_excel("./All-Chains-Balanced-Links/corpus_ALL_test.xlsx")

In [4]:
sub_corpus_files=ANCOR_dataframe["File_Name"].unique().tolist()
x=random.sample(sub_corpus_files,len(sub_corpus_files))
len(x)

255

In [ ]:
len(sub_corpus_files)

In [5]:
225*20/100

45.0

In [ ]:
x